services:
  superset:
    image: apache/superset:latest
    container_name: superset_app
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=my_super_secret_key
      - DATABASE_DB=superset
      - DATABASE_USER=superset
      - DATABASE_PASSWORD=superset
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    command: >
      bash -c "
      pip install psycopg2-binary &&
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin &&
      superset init &&
      gunicorn --bind 0.0.0.0:8088 'superset.app:create_app()'
      "

  db:
    image: postgres:16
    container_name: superset-db-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - superset_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: superset-redis-1
    ports:
      - "6379:6379"

volumes:
  superset_db_data:
